# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: InfraPipelinelVars
  - group: SubscriptionVars

stages:
  - stage: DevDeployment
    displayName: Deploy Dev Infrastructure
    jobs:
      - job: DeployInfrastructure
        displayName: Deploy Dev Infrastructure Bicep
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName: $(ResourceGroupName)dev-$(DeploymentDefaultLocation)
              csmFile: resources/main.bicep
              overrideParameters: '-storageAccountName $(storageAccountName)dev -location $(Location) -dataFactoryName $(DataFactoryName)dev'

      - job: DeployDevRoles
        displayName: Deploy Roles to RG
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName: $(ResourceGroupName)dev-$(DeploymentDefaultLocation)
              csmFile: resources/roles.bicep
              overrideParameters: '-scope $(devScope) -rgName $(ResourceGroupName)dev-$(DeploymentDefaultLocation)'

      - job: DeployDevBudget
        displayName: Deploy Basic Budget
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName: $(ResourceGroupName)dev-$(DeploymentDefaultLocation)
              csmFile: resources/budget.bicep

      - job: DeployDevKeyVault
        displayName: Deploy Key Vault Bicep
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName: $(ResourceGroupName)dev-$(DeploymentDefaultLocation)
              csmFile: resources/keyVault.bicep
              overrideParameters: '-tenantId $(tenantId) -spObjectId $(ServicePrincipleObjectId) -adfObjectId $(adfObjectIdDev) -location $(Location) -KeyVaultName $(KeyVaultNameDev)dev'
      - job: DeployDevFunctionApp
        displayName: Deploy function app to RG
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName: $(ResourceGroupName)dev-$(DeploymentDefaultLocation)
              csmFile: resources/functionApp.bicep
              overrideParameters: '-functionAppName $(functionAppName)dev -location $(Location) -functionStorageAccountName $(functionStorageAccountName)dev -serviceAppName $(functionAppName)dev'


  - stage: StageDeployment
    displayName: Deploy Stage Infrastructure
    jobs:
      - job: DeployInfrastructure
        displayName: Deploy Stage Infrastructure Bicep
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName: $(ResourceGroupName)stage-$(DeploymentDefaultLocation)
              csmFile: resources/main.bicep
              overrideParameters: '-storageAccountName $(storageAccountName)stage -location $(Location) -dataFactoryName $(DataFactoryName)stage'
      - job: DeployStageRoles
        displayName: Deploy Stage Roles to RG
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName:  $(ResourceGroupName)stage-$(DeploymentDefaultLocation)
              csmFile: resources/roles.bicep
              overrideParameters: '-scope $(stageScope) -rgName $(ResourceGroupName)stage-$(DeploymentDefaultLocation) -roleName stageReadRole'

      - job: DeployStageBudget
        displayName: Deploy Stage Basic Budget
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName:  $(ResourceGroupName)stage-$(DeploymentDefaultLocation)
              csmFile: resources/budget.bicep

      - job: DeployStageKeyVault
        displayName: Deploy Stage Key Vault Bicep
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName:  $(ResourceGroupName)stage-$(DeploymentDefaultLocation)
              csmFile: resources/keyVault.bicep
              overrideParameters: '-tenantId $(tenantId) -spObjectId $(ServicePrincipleObjectId) -location $(Location) -KeyVaultName $(KeyVaultName)stage'
      - job: DeployStageFunctionApp
        displayName: Deploy function app to RG
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName: $(ResourceGroupName)stage-$(DeploymentDefaultLocation)
              csmFile: resources/functionApp.bicep
              overrideParameters: '-functionAppName $(functionAppName)stage -location $(Location) -functionStorageAccountName $(functionStorageAccountName)stage -serviceAppName $(functionAppName)stage'


  - stage: ProdDeployment
    displayName: Deploy Prod Infrastructure
    jobs:
      - job: DeployInfrastructure
        displayName: Deploy Prod Infrastructure Bicep
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName: $(ResourceGroupName)prod-$(DeploymentDefaultLocation)
              csmFile: resources/main.bicep
              overrideParameters: '-storageAccountName $(storageAccountName)prod -location $(Location) -dataFactoryName $(DataFactoryName)prod'

      - job: DeployProdRoles
        displayName: Deploy Prod Roles to RG
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName:  $(ResourceGroupName)prod-$(DeploymentDefaultLocation)
              csmFile: resources/roles.bicep
              overrideParameters: '-scope $(prodScope) -rgName $(ResourceGroupName)stage-$(DeploymentDefaultLocation) -roleName prodReadRole'

      - job: DeployProdBudget
        displayName: Deploy Prod Basic Budget
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName:  $(ResourceGroupName)prod-$(DeploymentDefaultLocation)
              csmFile: resources/budget.bicep

      - job: DeployProdKeyVault
        displayName: Deploy Prod Key Vault Bicep
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName:  $(ResourceGroupName)prod-$(DeploymentDefaultLocation)
              csmFile: resources/keyVault.bicep
              overrideParameters: '-tenantId $(tenantId) -spObjectId $(ServicePrincipleObjectId) -location $(Location) -KeyVaultName $(KeyVaultName)prod'
      
      - job: DeployProdFunctionApp
        displayName: Deploy function app to RG
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              connectedServiceName: $(ServiceConnectionName)
              location: $(DeploymentDefaultLocation)
              resourceGroupName: $(ResourceGroupName)prod-$(DeploymentDefaultLocation)
              csmFile: resources/functionApp.bicep
              overrideParameters: '-functionAppName $(functionAppName)prod -location $(Location) -functionStorageAccountName $(functionStorageAccountName)prod -serviceAppName $(functionAppName)prod'


              