# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: install
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: PowerShell@2
        displayName: Install Terraform
        inputs:
          script: |
            Install-Module -Name Terraform -Force

  - job: init
    pool:
      vmImage: ubuntu-latest
    dependsOn: install
    steps:
      - task: TerraformInit@0
        displayName: Initialize Terraform
        inputs:
          workingDirectory: ./
          tfVersion: 1.1.7

  - job: plan
    pool:
      vmImage: ubuntu-latest
    dependsOn: init
    steps:
      - task: TerraformPlan@0
        displayName: Plan Terraform
        inputs:
          workingDirectory: ./
          tfVersion: 1.1.7

  - job: apply
    pool:
      vmImage: ubuntu-latest
    dependsOn: plan
    steps:
      - task: TerraformApply@0
        displayName: Apply Terraform
        inputs:
          workingDirectory: ./
          tfVersion: 1.1.7