# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run test for infrastructure'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# TODO Move to ADO/Pipeline variable/config
variables:
  ServiceConnectionName: 'Ivy Dev Data Platform' 
  EnvironmentType: 'Test'
  ResourceGroupName: 'rg-ivydataplatform-dev-eastus'
  DeploymentDefaultLocation: 'eastus' 

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy Infrastructure Bicep'
    inputs:
      deploymentScope: 'Resource Group'
      connectedServiceName: $(ServiceConnectionName)
      location: $(DeploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: resources/main.bicep
      # overrideParameters: >
      #   -environmentType $(EnvironmentType)
