# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

# TODO Move to ADO/Pipeline variable/config
variables:
- group: 'InfraPipelinelVars'  

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy Infrastructure Bicep'
    inputs:
      deploymentScope: 'Resource Group'
      connectedServiceName: 'Ivy Dev Data Platform' #'$(InfraPipelinelVars.ServiceConnectionName)'
      location: $(InfraPipelinelVars.DeploymentDefaultLocation)
      resourceGroupName: $(InfraPipelinelVars.ResourceGroupName)
      csmFile: resources/main.bicep
      # overrideParameters: >
      #   -environmentType '$(InfraPipelinelVars.EnvironmentType)'

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy Infrastructure Bicep'
    inputs:
      deploymentScope: 'Resource Group'
      connectedServiceName: 'Ivy Dev Data Platform' #'$(InfraPipelinelVars.ServiceConnectionName)'
      location: $(InfraPipelinelVars.DeploymentDefaultLocation)
      resourceGroupName: $(InfraPipelinelVars.ResourceGroupName)
      csmFile: resources/keyVault.bicep
      arguments: --param tenantId=$(InfraPipelinelVars.tenantId)
      # overrideParameters: >
      #   -environmentType '$(InfraPipelinelVars.EnvironmentType)'

      
